version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: setuptools
    versions:
    - 54.1.3
  - dependency-name: coveralls
    versions:
    - 3.0.1
  - dependency-name: ladybug-core
    versions:
    - 0.37.1
    - 0.37.2
    - 0.37.3
  - dependency-name: ladybug-geometry-polyskel
    versions:
    - 1.3.21
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
